travis:
  secure:
    BINSTAR_TOKEN: ZwO60DpVPjkN41vbHQ9QTJEon5ZuufaNdFQObZIiqvjJFJhtUTB+33fEYnoItQB7v/+jbCO0hSoeOQ8y1/5qzb2vmXuj41Yp8G4b/WjkNHxtIx3eu0A67FZ4hYi/zLRVHPXUYdEDyDApkUEySk5YvLYyyi7whHxGqFukSd4lo9qbYyGqpNA7oWKMNmcxKh4DCR5tNAseC2thzDfr89acwRnZz3WbS+F6ggITXQh5duO0dLtMdhBsHZQ4Y47T/Eom9BuKM8r/06cpHPuw01xnASwBTAOGoVYWe47cgFYPtNXbHUalOhxeSJFan/p05jVTsIeXr5+JWXKVWlgBlXARJfKMumYZP4u3yN+5Fnk77qJxn5bWrR/zvI/uS5fkfYxsR8MxWZRMRuQCaeCXfzTZp60CmfMYH869AO04qZVAdXdkUcWA48iK9CMqILf3n7qbtiPcZhxAcFW4TGNGeFgedLuQIvgxiU7IyufBV6rVCW2uIarywZfyGAkuAQHOJ/NaC7ZOTIp2D3aHLDAJvXJlOptpjeQIn7TB1YTUl7DGNkGyMu6GraJiKU2j/5rdHcxFXlice3UTOkD8pB49NUkMCR66H7bMZx/VUCucWm+moexIbjgOluZ62i1Jyd2SxtriT/3nGymR79N5wwieSEa7Qn93i663jeKlPFzpJ7fr7Y0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
