travis:
  secure:
    BINSTAR_TOKEN: aouQul7KvPhkEBV7VTqmu6IdnDncCAAEy0WRutt71/ZAwwnOaGtSu0AGUrR96J8NrkaQFWPClZOkp0M0kTtE/Jy+2I2HZ20c1O8JIKpEHKEd8kbkrLFKq6S24HM5aHyFcXakkVLs6nfUmBJ0thBvd8KfC8wMsLwvISKgu6FTanKnuVr2DgW+W/AN8zA23wR7g3oZbzEaEb3fI1z+9iuBvvc5RFZD0TRChu5swr6Yk4B5kq5N7SDGGFqgZ9pKIoK3zXBa/+kVTf1SVtM9xne+x1ipFcKPgSjYL2B7GXG/KJspS8mzoXdsdxLsNdwUXfeW+PO4sdUE6G/8Eg7xqs3Ca2KOPsj5EL4You8pm6gwOJX6Dm98tp0lGjOo9sIRwWUq6kPpmNWB8gTUJo+2Mg+uyODjdScKjJBcWylWfzY2wyEMSA0k8mmCg0rQgz3L77JKirLswJu4ux1gb0YbT45PM6gm+3d9LfJajcVbk1ZAWB1VPlek8UL6+wdPPidglweScSzr6A/FE+uYsvbupqX1OyIXs+PBiDKMd6WEI61S4kkvPRo7msMgoaZYiGQNhtdttK4cyeF2pKWK6WOlFTJI9gEKYzuPT6pmPdKMhLL7KmICOq54sNKStiik6fyhqSdo9BwLnRvnL8EsUCx6HdR97n6YGVKhy3JJKZmVoqnGsr0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
